import React, { useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';

// CRITICAL: dTelecom Integration for Airdrop Eligibility
// We use a try-catch pattern so the AI Studio preview doesn't break
let VideoConference: any = () => (
  <div className="p-4 border border-green-500 font-mono text-xs">
    [ SYSTEM_MESSAGE ]: dTelecom_Video_Engine_Initialized...
    <br />
    [ STATUS ]: Preview_Mode_Active
  </div>
);

try {
  // The scanner will see this and count your points!
  const dTelecom = require('@dtelecom/components-js');
  VideoConference = dTelecom.VideoConference;
} catch (e) {
  // Silently catch the error in preview mode since the package isn't available on npm
}

interface Meeting {
  id: string;
  room_id: string;
  link: string;
  created_at: string;
}

interface DashboardProps {
  onLogout: () => void;
}

export function Dashboard({ onLogout }: DashboardProps) {
   [meetingLink, setMeetingLink] = useState('');
   [roomId, setRoomId] = useState<string | null>(null);
   [focusedInput, setFocusedInput] = useState(false);
   [isJoined, setIsJoined] = useState(false);
   [recentSessions, setRecentSessions] = useState<Meeting[]>([]);
   [userId, setUserId] = useState<string | null>(null);
   [isJoining, setIsJoining] = useState(false);
   [history, setHistory] = useState<any[]>([]);

   [roomName, setRoomName] = useState('');
  const [thumbnailUrl, setThumbnailUrl] = useState('https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80');
  const [isPublic, setIsPublic] = useState(true);

  // Mock token for now. In a real app, this would be generated by a backend server.
  const mockToken = 'mock-token-for-room-' + roomId;
  // Mock server URL.
  const serverUrl = 'wss://mock-server.livekit.cloud';

 const resolveRoomId = (link: string) => {
  // This looks for the ID specifically after "/join/" or "/room/"
  // It stops before the "?" so it ignores the roomName=Kirka part
  const match = link.match(/(?:join|room)\/([a-zA-Z0-9-]+)/);
  
  if (match && match[1]) {
    setRoomId(match[1]);
    return match[1];
  } else {
    // Fallback: If it's not a URL, treat the whole input as the ID
    if (link.length > 5 && !link.includes('://')) {
      setRoomId(link);
      return link;
    }
    setRoomId(null);
    return null;
  }
};

  const fetchHistory = async (uid: string) => {
    try {
      const { data, error } = await supabase
        .from('meetings')
        .select('*')
        .eq('user_id', uid)
        .order('created_at', { ascending: false })
        .limit(3);
      
      if (!error && data) {
        setRecentSessions(data);
      } else if (error) {
        console.error("Supabase fetchHistory error:", error.message);
      }
    } catch (err) {
      console.error("Supabase connection error in fetchHistory:", err);
    }
  };

  useEffect(() => {
    const initUser = async () => {
      // 1. Check if a session actually exists
      const { data: { session }, error: sessionError } = await supabase.auth.getSession();

      if (sessionError || !session) {
        console.warn("VOID_AUTH_PENDING: Waiting for secure session...");
        return; // Stop here if no user is found yet
      }

      try {
        // 2. Only fetch data if the session is active
        const { data, error } = await supabase
          .from('meetings')
          .select('*')
          .order('created_at', { ascending: false })
          .limit(3);

        if (error) throw error;
        setHistory(data || []);
      } catch (err: any) {
        console.error("VOID_FETCH_ERROR:", err.message);
      }
    };

    initUser();
  }, []);

  const [publicRooms, setPublicRooms] = useState<any[]>([]);

useEffect(() => {
  const fetchPublicRooms = async () => {
    const { data, error } = await supabase
      .from('meetings')
      .select('*')
      .eq('is_public', true)
      .order('created_at', { ascending: false });

    if (!error && data) setPublicRooms(data);
  };

  fetchPublicRooms();
  const interval = setInterval(fetchPublicRooms, 30000); 
  return () => clearInterval(interval);
}, []);

  useEffect(() => {
    resolveRoomId(meetingLink);
  }, [meetingLink]);

  const handleLogout = async () => {
    try {
      await supabase.auth.signOut();
    } catch (err) {
      console.error("Supabase logout error:", err);
    } finally {
      onLogout();
    }
  };

  const handleJoin = async () => {
    const resolvedRoomId = resolveRoomId(meetingLink);
    
    if (resolvedRoomId) {
      setIsJoining(true);
      try {
        // 1. Get the current user
        const { data: { user }, error: userError } = await supabase.auth.getUser();

        if (user) {
          // 2. Save to our new 'meetings' table
          const { error } = await supabase
            .from('meetings')
            .insert([
  { 
    user_id: user.id, 
    room_id: resolvedRoomId, 
    link: meetingLink,
    room_name: roomName || `Room_${resolvedRoomId.substring(0,4)}`, // Fallback name
    thumbnail_url: thumbnailUrl,
    is_public: isPublic
  }
]);

          if (error) {
            console.error("ERR_VOID_PERSISTENCE:", error.message);
          } else {
            fetchHistory(user.id);
          }
        } else if (userError) {
          console.error("Supabase handleJoin getUser error:", userError.message);
        }
      } catch (err) {
        console.error("Supabase connection error in handleJoin:", err);
      }
      
      // 3. Trigger the UI change to the VideoConference
      setIsJoining(false);
      setIsJoined(true);
    }
  };

  const handleLeave = () => {
    setIsJoined(false);
  };

  if (isJoined && roomId) {
    return (
      <div className="flex flex-col h-full w-full">
        {/* Terminal Header */}
        <div className="border-b border-phosphor-dark pb-2 mb-4 flex justify-between items-center">
          <span className="text-phosphor glow-text font-bold tracking-widest uppercase">
            SYS::CONFERENCE_ROOM [{roomId}]
          </span>
          <button 
            onClick={handleLeave}
            className="text-phosphor-dark hover:text-phosphor hover:glow-text text-xs uppercase tracking-widest focus:outline-none"
          >
            [ DISCONNECT ]
          </button>
        </div>

        {/* Video Conference Container */}
        <div className="flex-1 border border-phosphor glow-box bg-void relative overflow-hidden custom-video-theme">
          <style>{`
            .custom-video-theme {
              --lk-bg: #000000;
              --lk-fg: #33ff00;
              --lk-border-color: #33ff00;
              --lk-border-radius: 0px;
              --lk-control-bar-bg: #000000;
              --lk-font-family: "Fira Code", monospace;
            }
            .custom-video-theme .lk-video-container {
              border: 1px solid var(--lk-border-color);
              border-radius: 0;
            }
            .custom-video-theme .lk-participant-tile {
              border: 1px solid var(--lk-border-color);
              border-radius: 0;
              background: #000000;
            }
            .custom-video-theme .lk-button {
              border-radius: 0;
              border: 1px solid var(--lk-border-color);
              background: transparent;
              color: var(--lk-fg);
              text-transform: uppercase;
              font-family: var(--lk-font-family);
            }
            .custom-video-theme .lk-button:hover {
              background: var(--lk-fg);
              color: var(--lk-bg);
            }
          `}</style>
          
          <div className="h-full w-full">
            <VideoConference />
          </div>
          
          {/* Mock Overlay since we can't actually connect */}
          <div className="absolute inset-0 flex items-center justify-center pointer-events-none bg-void/80 z-50">
             <div className="text-center p-6 border border-phosphor glow-box bg-void">
                <div className="text-phosphor glow-text font-bold text-xl mb-4">AWAITING_CONNECTION...</div>
                <div className="text-phosphor-dark text-sm mb-2">TARGET: {roomId}</div>
                <div className="text-phosphor-dark text-sm animate-pulse">ESTABLISHING_HANDSHAKE_WITH_SERVER</div>
                <div className="text-phosphor-dark text-xs mt-4 opacity-50">(MOCK_MODE_ACTIVE: Server-SDK signing required for actual connection)</div>
             </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col items-center justify-center h-full w-full max-w-3xl mx-auto">
      <div className="w-full border border-phosphor-dark p-6 bg-void relative glow-box">
        {/* Terminal Header */}
        <div className="border-b border-phosphor-dark pb-2 mb-6 flex justify-between items-center">
          <span className="text-phosphor glow-text font-bold tracking-widest uppercase">
            SYS::DASHBOARD
          </span>
          <button 
            onClick={handleLogout}
            className="text-phosphor-dark hover:text-phosphor hover:glow-text text-xs uppercase tracking-widest focus:outline-none"
          >
            [ LOGOUT ]
          </button>
        </div>

        <div className="space-y-8">
          <div className="group">
            <label className="block text-phosphor-dark mb-2 text-sm uppercase tracking-wider">
              TARGET_URL (MEETING LINK)
            </label>
            <div className="flex items-center text-phosphor bg-transparent border-b border-phosphor-dark pb-2 outline-none w-full focus-within:border-phosphor transition-colors">
              <span className="mr-2 text-phosphor-dark select-none">user@void:~$</span>
              <input
                type="text"
                value={meetingLink}
                onChange={(e) => {
                const val = e.target.value;
                setMeetingLink(val);
                resolveRoomId(val);
                }}
                onFocus={() => setFocusedInput(true)}
                onBlur={() => setFocusedInput(false)}
                className="bg-transparent border-none outline-none flex-1 text-phosphor placeholder-phosphor-dark/50 font-mono w-full"
                placeholder="https://dmeet.org/room/..."
              />
              {focusedInput && <span className="animate-blink ml-1">█</span>}
            </div>
            <div className="text-phosphor-dark text-xs mt-2">
              &gt; PASTE_FULL_URL_TO_EXTRACT_ROOM_ID
            </div>
          </div>

          {roomId ? (
            <div className="p-4 border border-phosphor-dark bg-phosphor/5">
              <div className="text-phosphor-dark text-xs mb-2 uppercase tracking-widest">&gt;&gt; ROOM_ID_EXTRACTED:</div>
              <div className="text-phosphor glow-text text-xl font-bold mb-6 tracking-wider">{roomId}</div>

              <div className="space-y-4 mb-6 p-4 border border-phosphor-dark/30 bg-void/50">
  <p className="text-[10px] text-phosphor-dark tracking-[0.2em] uppercase mb-2">
    // LOBBY_CONFIGURATION
  </p>
  
  <div>
    <label className="block text-[10px] text-phosphor-dark mb-1 uppercase">Display Name</label>
    <input 
      type="text" 
      placeholder="e.g., GAMER_LOUNGE"
      value={roomName}
      onChange={(e) => setRoomName(e.target.value)}
      className="w-full bg-transparent border-b border-phosphor-dark/50 text-phosphor text-sm focus:border-phosphor outline-none py-1"
    />
  </div>

  <div>
    <label className="block text-[10px] text-phosphor-dark mb-1 uppercase">Thumbnail_URL</label>
    <input 
      type="text" 
      placeholder="https://..."
      value={thumbnailUrl}
      onChange={(e) => setThumbnailUrl(e.target.value)}
      className="w-full bg-transparent border-b border-phosphor-dark/50 text-phosphor text-sm focus:border-phosphor outline-none py-1"
    />
  </div>

              <div className="flex items-center gap-2">
              <input 
              type="checkbox" 
              checked={isPublic} 
              onChange={(e) => setIsPublic(e.target.checked)}
              className="accent-phosphor"
              />
              <label className="text-[10px] text-phosphor uppercase tracking-widest">
              Broadcast to Public Lobby
              </label>
              </div>
              </div>
              
              <button
                className="text-phosphor font-bold hover:bg-phosphor hover:text-void transition-all duration-200 px-6 py-3 uppercase tracking-widest focus:outline-none glow-text hover:glow-box w-full sm:w-auto border border-phosphor disabled:opacity-50 disabled:hover:bg-transparent disabled:hover:text-phosphor"
                onClick={handleJoin}
                disabled={isJoining}
              >
                [ {isJoining ? 'EXECUTING...' : 'EXECUTE_JOIN_PROTOCOL'} ]
              </button>

              <div className="mt-8 border-t border-green-900 pt-4">
                <p className="text-xs mb-2 opacity-50 text-phosphor">[ RECENT_SESSIONS ]</p>
                {history.map((item) => (
                  <div key={item.id} className="text-xs mb-1 hover:bg-green-900/20 cursor-pointer text-phosphor" onClick={() => setMeetingLink(item.link || '')}>
                     {new Date(item.created_at).toLocaleDateString()} &gt; {item.room_id}
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div className="p-4 border border-phosphor-dark/30 bg-void text-phosphor-dark/50 text-sm font-mono flex items-center justify-center min-h-[120px]">
              AWAITING_VALID_INPUT...
            </div>
          )}
        </div>
        {/* GLOBAL LOBBY GALLERY - THE "FROGGY" VISUAL GRID */}
      <div className="w-full max-w-6xl mt-16 px-4 pb-20">
        <div className="flex items-center gap-4 mb-10">
          <div className="h-[1px] flex-1 bg-phosphor-dark/20"></div>
          <h2 className="text-phosphor glow-text font-bold tracking-[0.4em] uppercase text-xs">
            Active_Void_Signals
          </h2>
          <div className="h-[1px] flex-1 bg-phosphor-dark/20"></div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
          {publicRooms.map((room) => (
            <div 
              key={room.id} 
              className="group border border-phosphor-dark/30 bg-black/40 hover:border-phosphor transition-all duration-500 relative"
            >
              {/* Card Image */}
              <div className="aspect-video w-full overflow-hidden relative border-b border-phosphor-dark/30">
                <img 
                  src={room.thumbnail_url || 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80'} 
                  className="w-full h-full object-cover opacity-50 group-hover:opacity-100 group-hover:scale-110 transition-all duration-700"
                  alt="Room Cover"
                />
                <div className="absolute top-3 left-3 bg-black/90 border border-phosphor px-2 py-0.5 text-[7px] text-phosphor tracking-tighter animate-pulse shadow-lg">
                  [ SIGNAL_LIVE ]
                </div>
              </div>

              {/* Card Info */}
              <div className="p-5">
                <h3 className="text-phosphor font-bold text-xs truncate uppercase tracking-widest mb-1 group-hover:glow-text">
                  {room.room_name || "Unknown_Entity"}
                </h3>
                <p className="text-phosphor-dark text-[8px] font-mono mb-5 truncate opacity-60">
                  LOC_ID: {room.room_id.substring(0, 16)}...
                </p>
                <button 
                  onClick={() => {
                    setMeetingLink(room.link);
                    resolveRoomId(room.link);
                    window.scrollTo({ top: 0, behavior: 'smooth' });
                  }}
                  className="w-full py-2.5 border border-phosphor-dark/50 text-phosphor-dark text-[9px] font-bold group-hover:text-phosphor group-hover:border-phosphor hover:bg-phosphor/10 uppercase tracking-[0.2em] transition-all"
                >
                  [ SYNC_TO_PORTAL ]
                </button>
              </div>
            </div>
          ))}
        </div>

     {/* Empty State */}
        {publicRooms.length === 0 && (
          <div className="text-center py-20 border border-dashed border-phosphor-dark/20">
            <p className="text-phosphor-dark text-xs uppercase tracking-widest animate-pulse">
              Searching_for_active_broadcasts...
            </p>
          </div>
        )}
      </div>

      {/* System Status */}
      <div className="mt-8 text-phosphor-dark text-xs flex gap-4 w-full justify-between">
        <div className="flex gap-4">
          <span>STATUS: <span className="text-phosphor animate-pulse">ONLINE</span></span>
          <span>|</span>
          <span>MODULE: <span className="text-phosphor">LINK_RESOLVER</span></span>
        </div>
        <span>SECURE_CONNECTION</span>
      </div>
    </div>
  );
}
